#include <Keyboard.h>

int counter = 0;
int incomingByte = 0;
int start_print = 0;

void flush_serial_buffer(){
    while (Serial1.available()) 
      Serial1.read();
    while (Serial1.read() > 0) {}
    }

void print_serial() {
  counter++;
  Serial1.print("Command sent index is: ");
  Serial1.println(counter);
  delay(50);
  incomingByte = Serial1.read();
  if (incomingByte == 81 or incomingByte == 113) {
    delay(4);
      Serial1.println("QUITING...");
      delay(1000);
      flush_serial_buffer();
      setup();
      }
}

void wait_and_release() {
  delay(100); 
  Keyboard.releaseAll();
}

void setup() {
  counter = 0;
  Keyboard.begin();
  Serial1.begin(4800);
  delay(100);
  flush_serial_buffer();
  start_print = 0;
  Serial1.println();
  Serial1.println("*****************************************************************************************************");
  Serial1.println(".##....##.########.##....##.........########..########..########..######...######..########.########.");
  Serial1.println(".##...##..##........##..##..........##.....##.##.....##.##.......##....##.##....##.##.......##.....##");
  Serial1.println(".##..##...##.........####...........##.....##.##.....##.##.......##.......##.......##.......##.....##");
  Serial1.println(".#####....######......##....#######.########..########..######....######...######..######...########.");
  Serial1.println(".##..##...##..........##............##........##...##...##.............##.......##.##.......##...##..");
  Serial1.println(".##...##..##..........##............##........##....##..##.......##....##.##....##.##.......##....##.");
  Serial1.println(".##....##.########....##............##........##.....##.########..######...######..########.##.....##");
  Serial1.println("*****************************************************************************************************");
  Serial1.println("************               Developed by Andy Pazos - andy.pazos@gmail.com                ************");

  while (1) {
    if (start_print>=20){ 
        start_print=0;
        setup(); 
      }
    Serial1.println("Press SPACEBAR to start...");
    incomingByte = Serial1.read();
    if (incomingByte == 32) {    
      break;
    }
  delay(5000);
  start_print++;
  }
  flush_serial_buffer();
  Serial1.println("..............................[STARTED]................................");
  Serial1.println("You can quit by pressing 'q'....");
}

void loop() {
    Keyboard.begin();
    Keyboard.press(KEY_LEFT_GUI); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('A'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('B'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('C'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('I'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_SHIFT);wait_and_release();
    Keyboard.press(KEY_LEFT_SHIFT);wait_and_release(); 
    Keyboard.press(KEY_LEFT_SHIFT);wait_and_release();
    Keyboard.press(KEY_LEFT_SHIFT);wait_and_release();
    Keyboard.press(KEY_LEFT_SHIFT);wait_and_release();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('C'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT');	Keyboard.press('C'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('D'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('E'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('F'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('G'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('H'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('J'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('K'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('K'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('M'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('M'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('N'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('O'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('P'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('Q'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('R'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('S'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('S'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('T'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('U'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('V'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('W'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('X'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('Y'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('Z'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press(';'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('.'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press(','); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_TAB'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_LEFT_TAB'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_PAUSE'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_UP_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_DOWN_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_RIGHT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_UP_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_DOWN_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_LEFT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_RIGHT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_HOME'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('+'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('-'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('1'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('2'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('3'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('4'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('5'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('6'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('7'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('8'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('9'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('0'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('1'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('2'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('3'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('4'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('5'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('6'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('7'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('8'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('9'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('0'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('1'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('2'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('3'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('4'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('5'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('6'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('7'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('8'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('9'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('0'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('1'); wait_and_release();print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('2'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('3'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('4'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('5'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('6'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('7'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('8'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('9'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('0'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('1'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('2'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('3'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('4'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('5'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('6'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('7'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('8'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('9'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('0'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_ESCAPE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_TAB'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_F4'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_TAB'); wait_and_release(); print_serial(); 
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_TAB'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_SHIFT'); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_TAB'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_F4'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('\''); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('-'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('!'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('+'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('#'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('$'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('%'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('&'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('('); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press(')'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('*'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('+'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('.'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('/'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press(':'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press(';'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('?'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('@'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('['); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('\\'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press(']'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('^'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('_'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('{'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('|'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('}'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('~'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('<'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('='); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('>'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('0'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('1'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('2'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('3'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('4'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('5'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('6'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('7'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('8'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('9'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_F4'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('A'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('B'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_BACKSPACE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('C'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_CAPS_LOCK'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('D'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_DELETE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_DOWN_ARROW'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('E'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_RETURN'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_ESCAPE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('F'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('G'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('H'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('I'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('J'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('K'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('L'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_LEFT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('M'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('N'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_NUM_LOCK'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('O'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('P'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('Q'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('R'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_RETURN'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_RIGHT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('S'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_SCROLL_LOCK'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press(' '); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('T'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_TAB'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('U'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_UP_ARROW'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('V'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('W'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('X'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('Y'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('Z'); wait_and_release(); print_serial();
    Keyboard.press('KEY_PAUSE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('\`'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('-'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('!'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(' '); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('#'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('$'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('%'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('&'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('('); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(')'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('*'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(' '); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('.'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('/'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(':'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(' '); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('?'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('@'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('['); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('\\'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(']'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('^'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('_'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('\`'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('{'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('|'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('}'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('~'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('+'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('<'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('='); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('>'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('0'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('1'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('2'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('3'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('4'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('5'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('6'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('7'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('8'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('9'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('A'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('B'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_ESCAPE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_BACKSPACE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('C'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_CAPS_LOCK'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('D'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_DELETE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('E'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_RETURN'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_ESCAPE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('F'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('G'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('H'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('I'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('J'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('K'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('L'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('M'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('N'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_NUM_LOCK'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('O'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('P'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('Q'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('R'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_RETURN'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_RIGHT_ARROW'); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('S'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_SCROLL_LOCK'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(' '); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('T'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_TAB'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('U'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_UP_ARROW'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('V'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('W'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('X'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('Y'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('Z'); wait_and_release(); print_serial();
    Keyboard.press('KEY_END'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F1'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F10'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F11'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F12'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F13'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F14'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F15'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F16'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F17'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F18'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F19'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F2'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F20'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F22'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F23'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F24'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F3'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F4'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F5'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F6'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F7'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F8'); wait_and_release(); print_serial();
    Keyboard.press('KEY_F9'); wait_and_release(); print_serial();
    Keyboard.press('KEY_HOME'); wait_and_release(); print_serial();
    Keyboard.press('KEY_INSERT'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_0'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_1'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_2'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_3'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_4'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_5'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_6'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_7'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_8'); wait_and_release(); print_serial();
    Keyboard.press('KEY_KP_9'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_RETURN'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_ESCAPE'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('C'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('V'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('X'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_PRINT_SCREEN'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('R'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_PAUSE'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('D'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_F4'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_CTRL');  Keyboard.press('KEY_RIGHT_ARROW'); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('B'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press(' '); wait_and_release(); print_serial();
    Keyboard.press(KEY_LEFT_GUI); Keyboard.press('KEY_LEFT_SHIFT');  Keyboard.press('S'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_SHIFT'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_LEFT_SHIFT'); wait_and_release(); print_serial();
    Keyboard.press('KEY_LEFT_CTRL'); Keyboard.press('KEY_LEFT_ALT'); Keyboard.press('KEY_ESCAPE'); wait_and_release(); print_serial();
    delay(1000);
    Serial1.println(".............................[FINISHED]................................");
    delay(1000);
    setup();
}